name: firebase

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'amd64'
            platform: 'x64'
          - arch: 'arm64'
            platform: 'ARM64'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/compnerd/swift
          repository: thebrowsercompany/firebase-cpp-sdk

      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.intentionally_broken_like_upstream }}
          architecture: 'x64'

      - name: Install Desktop SDK prerequisites
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            python scripts/gha/install_prereqs_desktop.py --gha_build --arch '${{ matrix.arch }}'

      - name: Build SDK
        run:
          python3 .\scripts\gha\build_desktop.py --arch "${{ matrix.arch }}" --config "Release" --msvc_runtime_library "dynamic" --target firebase_app firebase_auth firebase_firestore --gha_build

      - name: Install firebase (manual)
        run: |
          New-Item -ItemType Directory -Path ${{ github.workspace }}/BuildRoot/Library/firebase/usr/include/firebase/firestore
          New-Item -ItemType Directory -Path ${{ github.workspace }}/BuildRoot/Library/firebase/usr/libs/windows

          Copy-Item "${{ github.workspace }}/build/external/src/firestore/Firestore/core/include/firebase/firestore/firestore_errors.h" "${{ github.workspace }}/BuildRoot/Library/firebase/usr/include/firebase/firestore/firestore_errors.h"
          Copy-Item "${{ github.workspace }}/build/external/src/firestore/Firestore/core/include/firebase/firestore/geo_point.h" "${{ github.workspace }}/BuildRoot/Library/firebase/usr/include/firebase/firestore/geo_point.h"
          Copy-Item "${{ github.workspace }}/build/external/src/firestore/Firestore/core/include/firebase/firestore/timestamp.h" "${{ github.workspace }}/BuildRoot/Library/firebase/usr/include/firebase/firestore/timestamp.h"

          Write-Host "Copying static libraries ..."
          $source = "${{ github.workspace }}/build"
          $libraries = Get-ChildItem -Path $source -File -Recurse -Filter *.lib
          foreach ($library in $libraries) {
            $destination = Join-Path -Path "${{ github.workspace }}/BuildRoot/Library/firebase/usr/libs/windows" -ChildPath $library.Name
            Copy-Item -Path $library.FullName -Destination $destination -Force
            Write-Host "... copied ${destination}"
          }
      - uses: actions/upload-artifact@v3
        with:
          name: firebase-windows-${{ matrix.arch }}
          path: ${{ github.workspace }}/BuildRoot/Library/firebase
