name: firebase

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/SourceCache/firebase-cpp-sdk
          ref: refs/heads/main
          repository: firebase/firebase-cpp-sdk

      - uses: compnerd/gha-setup-vsdevenv@main
        with:
          host_arch: amd64
          components: 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64'
          arch: amd64

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install absl-py
        run: pip install absl-py

      - name: Configure firebase
        run:
          cmake -B ${{ github.workspace }}/BinaryCache/firebase `
                -D BUILD_SHARED_LIBS=NO `
                -D CMAKE_BUILD_TYPE=Release `
                -D CMAKE_INSTALL_PREFIX=${{ github.workspace }}/BuildRoot/Library/firebase/usr `
                -G "Visual Studio 17 2022" `
                -A x64 `
                -S ${{ github.workspace }}/SourceCache/firebase-cpp-sdk `
                -D FIREBASE_CPP_BUILD_PACKAGE=YES `
                -D FIREBASE_INCLUDE_LIBRARY_DEFAULT=OFF `
                -D FIREBASE_INCLUDE_AUTH=YES `
                -D FIREBASE_INCLUDE_FIRESTORE=YES `
                -D FIREBASE_USE_BORINGSSL=YES
      - name: Build firebase
        run: cmake --build ${{ github.workspace }}/BinaryCache/firebase --config Release
      - name: Install firebase
        run: cmake --build ${{ github.workspace }}/BinaryCache/firebase --config Release --target install

      - uses: actions/upload-artifact@v3
        with:
          name: firebase-windows-amd64
          path: ${{ github.workspace }}/BuildRoot/Library/firebase

      - run: |
          echo build_tag=$(date +%Y%m%d.$(date +%-H/6 | bc)) >> ${GITHUB_ENV}

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.build_tag }}
          tag_name: ${{ env.build_tag }}

      - name: nuget package
        run: |
          $treeish = git log -1 --format=%h
          nuget pack -Properties DESTDIR=${{ github.workspace }}/BuildRoot/Library/firebase -Version 0.0.0.0-${treeish} ${{ github.workspace }}/SourceCache/firebase-cpp-sdk/firebase.nuspec
        shell: pwsh

      - name: publish nuget
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_USERNAME: thebrowsercompany-bot2
          NUGET_SOURCE_NAME: TheBrowserCompany
          NUGET_PUBLISH_URL: https://nuget.pkg.github.com/thebrowsercompany/index.json
        run: |
          nuget sources list | findstr "%NUGET_SOURCE_NAME%"
          if errorlevel 0 ( nuget sources remove -name %NUGET_SOURCE_NAME% )
          nuget sources Add -Name %NUGET_SOURCE_NAME% -Source %NUGET_PUBLISH_URL% -username %GITHUB_USERNAME% -password %GITHUB_TOKEN% -StorePasswordInClearText
          nuget setApiKey %GITHUB_TOKEN% -Source %NUGET_PUBLISH_URL%
          nuget push %GITHUB_WORKSPACE%\*.nupkg -Source %NUGET_SOURCE_NAME%
        shell: cmd

